### PR TITLE
Several fixes and enhancements for Codeface

### PR DESCRIPTION
**Pull request by clhunsen**
- move cppstats to most recent version (v0.9.2)
- some ducumentaion improvements
- some bugfixes
- add 'Base_Feature' for 'feature' analysis analogous to 'File_Level' in 'proximity' analysis
- fix date parsing in ML analysis
- fix NULL authors in ML analysis (props to @bockthom)

### CODE REVIEW

**Comment by clhunsen** [comment]
Any news on this?

**Comment by clhunsen** [comment]
Here an update on the things I have done since the original pull-request:
- add `messageId` and `creationDateOffset` columns in `mail` table
- add `--use--corpus` option to CLI to force `!use.mbox`
- fix several bugs, warnings and imperfections in ML-analysis function
- fix the ML test
- improve logging
- fix TravisCI scripts

**Comment by wolfgangmauerer** [comment]
Claus, I'm very sorry for getting back to this so late, but as you can see from the VCS activity, I needed some time to also do some actual development.
I have some comments/questions on a few of the patches, would you mind sending the stack via the mailing list so that I can comment on them? Thanks!

**Comment by clhunsen** [comment]
I have sent the patch stack to the mailing list some moments ago. Looking forward to your comments/questions.

**Comment by clhunsen** [comment]
The conflicts that are shown by GitHub are trivial to solve while merging:
- `datamodel/codeface_schema.sql`: I added two columns and changed one column type. The conflict occurs only on the empty comments (`COMMENT ''`) in the SQL file that has been removed in #55, but not on actually conflicting changes on the data model.
- `datamodel/codeface.mwb`: The changes I made on the SQL file simply need to be transferred to the binary `mwb` file.

**Comment by wolfgangmauerer** [comment]
(finally...) merged, thanks!

**Comment by clhunsen** [comment]
Yay! :tada:

**Pull request merged**
